<form enctype="multipart/form-data" action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=create" method="POST">

  <fieldset class="form-column">
        <div class="form-row">
            <label for="entitle">Titre</label>
            <input class="form-input" type="text" class="form-control" id="entitle" name="entitle" value="">
            
        </div>
        <div class="form-row">
            <label for="img">Image</label>
            <input class="form-input" type="text" class="form-control" id="img" name="img" value="">
           
        </div>
        
        <div class="form-row">
			<label for="pet-select">Période</label>			
            <select name="periods_name">
               <?php foreach($tplVars['periods'] as $period): ?>
               <option valeur="<?= htmlspecialchars($period['ID']); ?>"><?= htmlspecialchars($period['Name']); ?></option>
               <?php endforeach; ?>
            </select>
        </div>
            <div class="button-group">
                <button>Enregistrer</button>
                <a class="button btn-cancel" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=index">Annuler</a>

            </div>
        
    </fieldset>
    
    

</form>

