
	    
		<section class="display-section">
				
			
			
			
		    <table>
		        
		        <caption>Période : <?= htmlspecialchars($tplVars['PeriodTopics']['Name']); ?> / Thème : <?= htmlspecialchars($tplVars['PeriodTopics']['Entitle']); ?></caption>
                 <tr>
                     <th>Questions</th>
                    
                    
                     <th>Actions sur la question</th>
                 </tr>
                 
                 <?php foreach($tplVars['listsQuestions'] as $listsQuestion): ?>
                 <tr>
                     <td><?= htmlspecialchars($listsQuestion['Entitle']); ?></td>
                    
                     <td>
                         <div class="form-row-topics">
                             <a class="admin-button" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=editFormQuestion&qid=<?= htmlspecialchars($listsQuestion['ID']); ?>">Modifier</a></td>
                         </div>
                     </td>
                    
                 </tr>
                <?php endforeach;?>
             </table>
    
		    
	    </section>

