<form enctype="multipart/form-data" action="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=create" method="POST">

  <fieldset class="form-column">
        <div class="form-row">
            <label for="name">Titre</label>
            <input class="form-input" type="text" class="form-control" id="name" name="name" value="">
            
        </div>
        <div class="form-row">
            <label for="img">Image</label>
            <input class="form-input" type="text" class="form-control" id="img" name="img" value="">
           
        </div>
        <div class="form-column">
            <label for="name">Description</label>
            <textarea class="form-textarea" id="description" name="description">
                
            </textarea> 
       
        </div>
            <div class="button-group">
                <button>Enregistrer</button>
                <a class="button btn-cancel" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=index">Annuler</a>

            </div>
        
    </fieldset>
    
    

</form>

