
	    
		<section class="display-section">
				
		    <table>
         <tr>
             <th>Questions</th>
             <th>Périodes</th>
             <th>Sujets</th>
             <th>Action</th>
         </tr>
      
          <?php foreach($tplVars['listsQuestions'] as $listsQuestion): ?>
         <tr>
             <td><?= htmlspecialchars($listsQuestion['Entitle']); ?></td>
             <td><?= htmlspecialchars($listsQuestion['Name']); ?></td>
             <td><?= htmlspecialchars($listsQuestion['TopicsName']); ?></td>
             <td>
                <div class="form-row-topics">
                    <a class="admin-button " href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=editFormPeriodName&id=<?= intval($listsQuestion['ID']);?>">Modifier</a>
                    <a class="admin-button admin-button-delete " href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=delete&id=<?= intval($listsQuestion['ID']);?>">Supprimer</a></td>
                </div>
             </td>
         </tr>
          <?php endforeach; ?>
      </table>
      
      <div class="">
        <a class="admin-button admin-button-add" href="<?= $tplVars['WWW_URL']; ?>index.php?controller=Admin\<?= $tplVars['crud'];?>&task=newForm"> Ajouter un Thème</a>
      </div>     
            
		    
	    </section>

